name: recipe_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  appkit_ui_element_colors: ^1.0.0
  bitsdojo_window: ^0.1.6
  fluent_ui: ^4.9.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_markdown: ^0.7.4+3
  go_router: ^16.0.0
  macos_ui: ^2.0.9
  provider: ^6.1.2
  system_theme: ^3.1.2
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  cupertino_icons: ^1.0.0
  flutter_svg: ^2.0.16
  cupertino_sidebar: ^1.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  brick_offline_first_with_supabase: ^2.1.0
  sqflite: ^2.4.1
  brick_sqlite: ^4.1.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.3
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.4+4
  flutter_dotenv: ^5.2.1
  test: ^1.25.8
  pull_down_button: ^0.10.2
  modal_bottom_sheet: ^3.0.0
  sheet: ^1.0.0
  wolt_modal_sheet: ^0.11.0
  wolt_responsive_layout_grid: ^0.0.3
  flutter_form_builder: ^9.6.0
  form_builder_extra_fields: ^11.1.0
  form_builder_cupertino_fields:
    path: /Users/matt/repos/form_builder_cupertino_fields
  super_context_menu: ^0.9.1
  flutter_fast_forms: ^18.0.0
  drift_sqlite_async: ^0.2.1
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  powersync: ^1.11.3
  sqlite3_flutter_libs: ^0.5.32
  sqlite3: ^2.0.0
  postgres: ^3.5.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.3
  flutter_image_compress: ^2.4.0
  nanoid: ^1.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  porter_2_stemmer: ^3.0.2
  characters: ^1.4.0
  mecab_dart:
    path: /Users/matt/repos/mecab_dart
  archive: ^4.0.5
  super_cupertino_navigation_bar: ^2.1.2
  disclosure: ^2.2.0
  freezed_annotation: ^3.1.0
  http: ^1.1.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  sign_in_button: ^4.0.1
  crypto: ^3.0.3
  purchases_flutter: ^9.0.0-beta.1
  purchases_ui_flutter: ^9.0.0-beta.1
  flutter_slidable: ^4.0.0
  package_info_plus: ^8.0.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.5
  brick_offline_first_with_supabase_build: ^2.0.0
  shared_preferences: any
  drift: ^2.23.1
  drift_dev: ^2.23.1
  mockito: ^5.4.5
  fake_async: ^1.3.2
  freezed: ^3.0.6

dependency_overrides:
  intl: ^0.20.2

flutter:
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Unna-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/samples/
    - assets/ipadic.tar.xz
    - assets/recipes.json
    - assets/recipes-matt.json
    # Help documentation
    - assets/docs/quick-questions/
    - assets/docs/learn-more/
    - assets/docs/troubleshooting/
